# Generated by Django 2.2 on 2020-12-29 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=200)),
                ('modeldescription', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('softwaretype', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppliername', models.CharField(max_length=200, null=True)),
                ('pmname', models.CharField(blank=True, max_length=200, null=True)),
                ('supplier_description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(blank=True, max_length=200, null=True)),
                ('software_full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('model_sw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aspmissue.ModelName')),
                ('software_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aspmissue.SoftwareType')),
            ],
        ),
        migrations.AddField(
            model_name='modelname',
            name='modeltype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aspmissue.ModelType'),
        ),
        migrations.AddField(
            model_name='modelname',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aspmissue.Supplier'),
        ),
        migrations.CreateModel(
            name='IssueSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_analysis_version_wise', models.CharField(max_length=200, null=True)),
                ('issue_number_version_wise', models.IntegerField(max_length=2000, null=True)),
                ('expected_software_date', models.DateField(blank=True, null=True)),
                ('actual_software_date', models.DateField(null=True)),
                ('feedback_expected_date', models.DateField(null=True)),
                ('feedback_actual_date', models.DateField(null=True)),
                ('new_issue_number', models.IntegerField(max_length=200, null=True)),
                ('reopen_issue_number', models.IntegerField(max_length=200, null=True)),
                ('is_mp', models.BooleanField(default=False)),
                ('closed_issue', models.IntegerField(max_length=200, null=True)),
                ('delay', models.CharField(blank=True, choices=[('PM', 'PM'), ('QC', 'QC'), ('Supplier', 'Supplier')], max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('delay_by_pm', models.CharField(blank=True, max_length=200, null=True)),
                ('delay_by_qc', models.CharField(blank=True, max_length=200, null=True)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aspmissue.ModelName')),
                ('software', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aspmissue.Software')),
            ],
        ),
        migrations.CreateModel(
            name='IssueAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_name', models.CharField(max_length=200, null=True)),
                ('imei', models.CharField(max_length=200, null=True)),
                ('issue_source', models.CharField(max_length=200, null=True)),
                ('problem', models.CharField(max_length=2000, null=True)),
                ('qc_findings', models.TextField(null=True)),
                ('hw_findings', models.TextField(null=True)),
                ('root_cause', models.TextField(blank=True, null=True)),
                ('evidence', models.FileField(upload_to='')),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aspmissue.ModelName')),
            ],
        ),
    ]
