# Generated by Django 2.2 on 2020-12-29 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aspmissue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuesummary',
            name='software',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aspmissue.Software'),
        ),
    ]
