# Generated by Django 2.2 on 2020-12-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspmissue', '0003_auto_20201229_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuesummary',
            name='issue_clsoed_by_pm',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='issuesummary',
            name='supplier_can_not_fixed',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
