# Generated by Django 2.2 on 2021-01-10 06:04

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aspmissue', '0006_majorissue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorissue',
            name='issue',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Camera Blur', 'Camera Blur'), ('Sound Noise', 'Sound Noise'), ('Network', 'Network'), ('Camera Noise', 'Camera Noise')], max_length=200, null=True),
        ),
    ]
