# Generated by Django 2.2 on 2021-01-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspmissue', '0007_auto_20210110_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelname',
            name='isFinished',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
