# Generated by Django 3.1.4 on 2021-02-08 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aspmissue', '0008_modelname_isfinished'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_analysis_version_wise', models.CharField(max_length=200, null=True)),
                ('total_issue', models.IntegerField(max_length=2000, null=True)),
                ('expected_software_date', models.DateField(blank=True, null=True)),
                ('actual_software_date', models.DateField(null=True)),
                ('feedback_expected_date', models.DateField(null=True)),
                ('feedback_actual_date', models.DateField(null=True)),
                ('new_issue', models.IntegerField(max_length=200, null=True)),
                ('reopen_issue', models.IntegerField(max_length=200, null=True)),
                ('is_mp', models.BooleanField(default=False)),
                ('closed_issue', models.IntegerField(max_length=200, null=True)),
                ('supplier_can_not_fixed', models.IntegerField(blank=True, max_length=200, null=True)),
                ('issue_clsoed_by_pm', models.IntegerField(blank=True, max_length=200, null=True)),
                ('delay', models.CharField(blank=True, choices=[('PM', 'PM'), ('QC', 'QC'), ('Supplier', 'Supplier')], max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('delay_by_pm', models.CharField(blank=True, max_length=200, null=True)),
                ('delay_by_qc', models.CharField(blank=True, max_length=200, null=True)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aspmissue.modelname')),
                ('software', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aspmissue.software')),
            ],
        ),
    ]
