# Generated by Django 2.2 on 2021-02-10 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aspmissue', '0010_auto_20210208_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aspmissue.Supplier'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='mejor_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aspmissue.MajorIssue'),
        ),
    ]
