# Generated by Django 2.2 on 2021-02-10 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aspmissue', '0011_auto_20210210_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuesummary',
            name='mejor_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aspmissue.MajorIssue'),
        ),
    ]
