# Generated by Django 3.1.4 on 2021-03-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspmissue', '0014_issuesummary_diff_two_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuesummary',
            name='diff_two_version',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
