# Generated by Django 3.1.4 on 2021-03-10 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspmissue', '0015_auto_20210310_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuesummary',
            old_name='previous_software_date',
            new_name='pre_version_actual_software_date',
        ),
    ]
