# Generated by Django 2.2 on 2021-03-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspmissue', '0016_auto_20210310_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuesummary',
            name='pre_version_actual_software_date',
            field=models.DateField(null=True),
        ),
    ]
