# Generated by Django 3.1.4 on 2021-05-06 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspmissue', '0017_auto_20210315_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuesummary',
            name='diff_two_version',
        ),
        migrations.RemoveField(
            model_name='issuesummary',
            name='pre_version_actual_software_date',
        ),
    ]
