# Generated by Django 3.1.4 on 2021-05-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspmissue', '0018_auto_20210506_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuesummary',
            old_name='closed_issue',
            new_name='Fixed_issue',
        ),
        migrations.RenameField(
            model_name='issuesummary',
            old_name='total_issue',
            new_name='Remaining_issue',
        ),
        migrations.AlterField(
            model_name='issuesummary',
            name='issue_clsoed_by_pm',
            field=models.IntegerField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='issuesummary',
            name='software',
            field=models.CharField(default='No software available Now', max_length=200),
        ),
        migrations.AlterField(
            model_name='issuesummary',
            name='supplier_can_not_fixed',
            field=models.IntegerField(default=0, max_length=200),
        ),
    ]
