# Generated by Django 3.1.4 on 2021-05-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspmissue', '0019_auto_20210508_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuesummary',
            name='existing_issue',
            field=models.IntegerField(blank=True, default=0, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='issuesummary',
            name='software_type',
            field=models.CharField(choices=[('Version Software', 'Version Software'), ('Demo Software', '\tDemo Software'), ('Final MP SW', 'Final MP SW'), ('Compatibility SW', 'Compatibility SW')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='issuesummary',
            name='Fixed_issue',
            field=models.IntegerField(default=0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='issuesummary',
            name='Remaining_issue',
            field=models.IntegerField(default=0, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='issuesummary',
            name='new_issue',
            field=models.IntegerField(default=0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='issuesummary',
            name='reopen_issue',
            field=models.IntegerField(default=0, max_length=200, null=True),
        ),
    ]
