# Generated by Django 3.1.4 on 2021-05-20 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aspmissue', '0020_auto_20210508_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuesummary',
            name='Fixed_issue',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='issuesummary',
            name='Remaining_issue',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='issuesummary',
            name='existing_issue',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='issuesummary',
            name='issue_clsoed_by_pm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='issuesummary',
            name='new_issue',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='issuesummary',
            name='reopen_issue',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='issuesummary',
            name='software',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='issuesummary',
            name='supplier_can_not_fixed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='modelname',
            name='modelname',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='AfterSalesAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_version', models.CharField(max_length=200)),
                ('target_version', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Improvement', 'Improvement'), ('Improvement', 'Improvement')], max_length=200)),
                ('validation', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200)),
                ('details', models.TextField(blank=True, null=True)),
                ('solved_or_improved', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('model_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aspmissue.modelname')),
            ],
        ),
    ]
