# Generated by Django 3.1.4 on 2021-05-22 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspmissue', '0022_auto_20210520_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='aftersalesanalysis',
            name='feedback_date',
            field=models.DateField(default=datetime.date(2021, 5, 22)),
        ),
        migrations.AlterField(
            model_name='aftersalesanalysis',
            name='issue_or_improvement_details',
            field=models.TextField(blank=True, help_text='Example: Update the google patch, Lock and Unlock Icon change.....', null=True),
        ),
        migrations.AlterField(
            model_name='aftersalesanalysis',
            name='solved_or_improved',
            field=models.TextField(blank=True, help_text=' Example : Update the google patch – Not Fixed ( According to ASPM realease note ). Ø Change existing default wallpaper (add new wallpaper)....', null=True),
        ),
    ]
