# Generated by Django 3.1.4 on 2021-05-24 06:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aspmissue', '0023_auto_20210522_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterSalesIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_version', models.CharField(max_length=200)),
                ('target_version', models.CharField(max_length=200)),
                ('feedback_date', models.DateField(default=datetime.date(2021, 5, 24))),
                ('type', models.CharField(choices=[('Improvement', 'Improvement'), ('Market Issue', 'Market Issue')], max_length=200)),
                ('validation', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200)),
                ('issue_or_improvement_details', models.TextField(blank=True, help_text='Example: Update the google patch, Lock and Unlock Icon change.....', null=True)),
                ('solved_or_improved', models.TextField(blank=True, help_text=' Example : Update the google patch – Not Fixed ( According to ASPM realease note ). Ø Change existing default wallpaper (add new wallpaper)....', null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('model_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aspmissue.modelname')),
            ],
        ),
        migrations.CreateModel(
            name='FieldTestReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(max_length=200)),
                ('ft_status', models.CharField(choices=[('Passed', 'Passed'), ('Failed', 'Failed')], max_length=20)),
                ('ft_date', models.DateField()),
                ('bottolneck', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('model_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aspmissue.modelname')),
            ],
        ),
        migrations.DeleteModel(
            name='AfterSalesAnalysis',
        ),
    ]
