# Generated by Django 3.1.4 on 2021-05-24 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspmissue', '0024_auto_20210524_1217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AfterSalesIssue',
            new_name='AfterSalesAnalysis',
        ),
    ]
