# Generated by Django 3.1.4 on 2021-05-29 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aspmissue', '0026_auto_20210529_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuesummary',
            name='software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aspmissue.software'),
        ),
    ]
