# Generated by Django 3.1.4 on 2021-05-29 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspmissue', '0027_auto_20210529_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelname',
            name='modeltype',
        ),
    ]
