# Generated by Django 3.1.4 on 2021-05-29 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aspmissue', '0028_remove_modelname_modeltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aftersalesanalysis',
            name='source_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aspmissue.software'),
        ),
        migrations.AlterField(
            model_name='fieldtestreport',
            name='software_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aspmissue.software'),
        ),
    ]
