# Generated by Django 3.1.4 on 2021-05-29 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspmissue', '0029_auto_20210529_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='software_type',
        ),
    ]
