# Generated by Django 3.1.4 on 2021-06-01 07:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aspmissue', '0030_remove_software_software_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aftersalesanalysis',
            name='feedback_date',
            field=models.DateField(default=datetime.date(2021, 6, 1)),
        ),
        migrations.CreateModel(
            name='OTATestReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField(default=datetime.date(2021, 6, 1))),
                ('target_version', models.CharField(max_length=200)),
                ('test_type', models.CharField(choices=[('Self_OTA', 'Self_OTA'), ('G_OTA', 'G_OTA')], max_length=200)),
                ('is_MP_when_Test', models.CharField(choices=[('N/A', 'N/A'), ('Improvement SW', 'Improvement SW')], max_length=200)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('evidence_Uploaded_to_QC_Server', models.BooleanField(default=True)),
                ('model_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aspmissue.modelname')),
                ('source_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aspmissue.software')),
            ],
        ),
    ]
